---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: participant
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  participant.conf: |
    canton {
      participants {
        {{ .Values.participantName }} {
          {{- include "canton.storage" . | indent 10 }}

          ledger-api {
            address = "0.0.0.0"
            port = {{ .Values.ports.public }}
            {{- if .Values.tls.public.enabled }}
            tls {
              cert-chain-file = {{ .Values.tls.public.chain | quote }}
              private-key-file = {{ .Values.tls.public.key | quote }}
              {{- if .Values.mtls.public.enabled }}
              {{- if ne .Values.mtls.public.ca "" }}
              trust-collection-file = {{ .Values.mtls.public.ca | quote }}
              {{- end }}
              client-auth = {
                type = "require"
                admin-client {
                  cert-chain-file = {{ .Values.mtls.public.chain | quote }}
                  private-key-file = {{ .Values.mtls.public.key | quote }}
                }
              }
              {{- end }}
              minimum-server-protocol-version = {{ include "canton.tls.minimumServerProtocolVersion" .Values.tls.public.minimumServerProtocolVersion }}
              ciphers = {{ include "canton.tls.ciphers" .Values.tls.public.ciphers }}
            }
            {{- end }}

            {{- if .Values.authServices.enabled }}
            auth-services = [{
              {{- include "participant.authServicesType" . | nindent 14 }}
              {{- with .Values.authServices.targetAudience }}
              target-audience = {{ . | quote }}
              {{- end }}
            }]
            {{- with .Values.authServices.additionalAdminUserId }}
            user-management-service = {
              additional-admin-user-id = {{ . | quote }}
            }
            {{- end }}
            {{- end }}
          }

          admin-api {
            address = "0.0.0.0"
            port = {{ .Values.ports.admin }}
            {{- if .Values.tls.admin.enabled }}
            tls {
              cert-chain-file = {{ .Values.tls.admin.chain | quote }}
              private-key-file = {{ .Values.tls.admin.key | quote }}
              {{- if .Values.mtls.admin.enabled }}
              {{- if ne .Values.mtls.admin.ca "" }}
              trust-collection-file = {{ .Values.mtls.admin.ca | quote }}
              {{- end }}
              client-auth = {
                type = "require"
                admin-client {
                  cert-chain-file = ""
                  private-key-file = ""
                }
              }
              {{- end }}
              minimum-server-protocol-version = {{ include "canton.tls.minimumServerProtocolVersion" .Values.tls.admin.minimumServerProtocolVersion }}
              ciphers = {{ include "canton.tls.ciphers" .Values.tls.admin.ciphers }}
            }
            {{- end }}
          }

          init.parameters.unique-contract-keys = {{ .Values.uniqueContractKeys }}

          replication.enabled = true

          monitoring.grpc-health-server {
            address = "0.0.0.0"
            port = {{ .Values.ports.health }}
          }
        }
      }

      {{ if .Values.metrics.enabled -}}
      monitoring.metrics {
        report-jvm-metrics = yes
        reporters = [{
          type = prometheus
          address = "0.0.0.0"
          port = {{ .Values.ports.metrics }}
        }]
      }
      {{- end }}
    }
  {{- with .Values.configOverride }}
  participant-override.conf: |
  {{- . | nindent 4 }}
  {{- end }}
