{{- if and .Values.metrics.enabled .Values.metrics.podMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "common.fullname" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: participant
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.metrics.podMonitor.jobLabel }}
  jobLabel: {{ . }}
  {{- end }}
  {{- with .Values.metrics.podMonitor.podTargetLabels }}
  podTargetLabels: {{- toYaml . | nindent 4 }}
  {{- end }}
  podMetricsEndpoints:
    - port: metrics
    {{- with .Values.metrics.podMonitor.extraPodMetricsEndpoints }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    matchLabels: {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: participant
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  {{- with .Values.metrics.podMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
  {{- with .Values.metrics.podMonitor.targetLimit }}
  targetLimit: {{ . }}
  {{- end }}
  {{- with .Values.metrics.podMonitor.labelLimit }}
  labelLimit: {{ . }}
  {{- end }}
  {{- with .Values.metrics.podMonitor.labelNameLengthLimit }}
  labelNameLengthLimit: {{ . }}
  {{- end }}
  {{- with .Values.metrics.podMonitor.labelValueLengthLimit }}
  labelValueLengthLimit: {{ . }}
  {{- end }}
{{- end }}
