{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.fullname" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: common
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- with .Values.serviceAccount.imagePullSecrets }}
imagePullSecrets: {{- toYaml . | nindent }}
{{- end }}
{{- with .Values.serviceAccount.imagePullSecrets }}
secrets: {{- toYaml . | nindent }}
{{- end }}
{{- end }}
