{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.serviceAccountName" (list . "") }}
  {{- with .Values.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: participant
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
secrets:
  {{- with .Values.storage.existingSecret.name }}
  - name: {{ . }}
  {{- end }}
  {{- if .Values.environmentSecrets }}
  - name: {{ template "common.fullname" . }}-secretmap
  {{- end }}
  {{- with .Values.serviceAccount.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
