---
apiVersion: v2
name: "daml-http-json"
version: 0.0.6
appVersion: 2.6.0
kubeVersion: ">= 1.21.0-0"
description: "A Helm chart for Daml HTTP JSON API service"
home: https://github.com/DACH-NY/daml-enterprise-k8s-support/tree/main/charts/daml-http-json
icon: https://raw.githubusercontent.com/DACH-NY/daml-enterprise-k8s-support/main/images/daml-logo.png
keywords:
  - api
  - daml
  - http
  - json
  - ledger
  - service
maintainers:
  - name: "Digital Asset"
    url: https://github.com/DACH-NY/
sources:
  - https://docs.daml.com/json-api/index.html
annotations:
  artifacthub.io/license: Apache-2.0
