---
apiVersion: v2
name: "daml-http-json"
version: 0.1.0
appVersion: 2.6.4
kubeVersion: ">= 1.22.0-0"
description: "A Helm chart for Daml HTTP JSON API service"
home: https://github.com/digital-asset/daml-helm-charts/tree/main/charts/daml-http-json
icon: https://raw.githubusercontent.com/digital-asset/daml-helm-charts/main/images/daml-logo.png
keywords:
  - api
  - daml
  - http
  - json
  - ledger
  - service
maintainers:
  - name: "Digital Asset"
    url: https://github.com/digital-asset/
sources:
  - https://docs.daml.com/json-api/index.html
annotations:
  artifacthub.io/license: Apache-2.0
