---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canton-node.fullname" . }}-mediator
  labels: {{- include "canton-node.labels" (list . "common") | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  mediator.conf: |
    canton {
      mediators {
        {{ .Values.common.mediatorName }} {
          {{- include "canton-node.storage" (list . "mediator") | indent 10 }}

          admin-api {
            address = "0.0.0.0"
            port = {{ .Values.mediator.ports.admin }}
            {{- include "canton-node.adminTLS" (list .Values.common.tls.admin) | indent 12 }}
          }

          replication {
            enabled = true
          }

          monitoring.grpc-health-server {
            address = "0.0.0.0"
            port = {{ .Values.mediator.ports.health }}
          }
        }
      }

      {{ include "canton-node.remote-sequencers" . | nindent 6 | trim }}

      {{- include "canton-node.monitoring" (list . "mediator") | nindent 6 }}
    }
