---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "canton-node.fullname" . }}-mediator
  {{- with .Values.mediator.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "canton-node.labels" (list . "mediator") | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.mediator.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.mediator.service.type }}
  ports:
    - name: admin
      protocol: TCP
      port: {{ .Values.mediator.service.ports.admin }}
      targetPort: admin
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.mediator.service.ports.metrics }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "canton-node.selectorLabels" (list . "mediator") | nindent 4 }}
