---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}
  {{- with .Values.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "common.selectorLabels" . | nindent 6 }}
  {{- with .Values.deployment.strategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        "checksum/config": {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
        "checksum/env": {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum | quote }}
        "checksum/secret": {{ include (print $.Template.BasePath "/secret-env.yaml") . | sha256sum | quote }}
        {{- with .Values.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels" . | nindent 8 }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "common.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: http-json
          image: {{ include "common.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          args:
            - "--config=/etc/http-json/json.conf"
            - "--log-level={{ .Values.logLevel }}"
            - "--log-encoder={{ .Values.logEncoder }}"
          envFrom:
            {{- if .Values.environment }}
            - configMapRef:
                name: {{ include "common.fullname" . }}-envmap
            {{- end }}
            {{- if .Values.environmentSecrets }}
            - secretRef:
                name: {{ include "common.fullname" . }}-secretmap
            {{- end }}
          {{- if .Values.storage.existingSecret.name }}
          env:
            - name: JSON_API_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.existingSecret.name }}
                  key: {{ .Values.storage.existingSecret.key }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.ports.http }}
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.ports.metrics }}
            {{- end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            timeoutSeconds: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            timeoutSeconds: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /etc/http-json/json.conf
              subPath: json.conf
              readOnly: true
            {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: "/tls"
              readOnly: true
            {{- if .Values.mtls.enabled }}
            - name: mtls
              mountPath: "/mtls"
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if .Values.storage.certificatesSecret }}
            - name: pgtls
              mountPath: "/pgtls"
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" . }}
        {{- if and .Values.tls.enabled .Values.tls.certManager.issuerName }}
        # Dummy certificate only used to mount the root CA certificate
        {{- include "certManager.csi" (list . "" "tls" .Values.tls.certManager "") | indent 8 }}
        {{- if and .Values.mtls.enabled .Values.mtls.certManager.issuerName }}
        {{- include "certManager.csi" (list . "" "mtls" .Values.mtls.certManager "") | indent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.storage.certificatesSecret }}
        - name: pgtls
          secret:
            secretName: {{ .Values.storage.certificatesSecret }}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
