{{- if .Values.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "canton-trigger.fullname" . }}-secretmap
  labels: {{- include "canton-trigger.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $key,$value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
