---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "canton-trigger.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "canton-trigger.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.ports.http }}
      targetPort: http
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
    {{- end }}
  selector:
    {{- include "canton-trigger.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.sessionAffinity.enabled }}
  sessionAffinity: "ClientIP"
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinity.timeout }}
  {{- end }}
