# Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 2.1

env: &env
  TERM: dumb
  CI: "true"
  USER: circleci

executors:
  chart-releaser:
    docker:
       - image: quay.io/helmpack/chart-releaser:v1.5.0
    environment:
      LC_ALL: "C.UTF-8"
    resource_class: small

commands:
  build-cr:
    steps:
      - run:
          command: apk add helm yq github-cli git jq openssh bash
          name: Install dependencies for the chart publish image
  deploy-cr:
    steps:
      - run:
          command: ./scripts/chart_publish.sh $GH_TOKEN
          name: Run the release script

jobs:
  build:
    docker:
    - image: cimg/base:2021.04
    environment:
      <<: *env
    steps:
      - checkout
      - run:
         name: build
         command: |
           set -euo pipefail
           echo "Success!"
  release-chart:
    executor: chart-releaser
    steps:
      - build-cr
      - checkout
      - deploy-cr

workflows:
  releaser:
    jobs:
      - build
      - approve_release_helm_charts:
          type: approval
      - release-chart:
          requires: 
           - approve_release_helm_charts
          filters:
            branches:
              only: main