# Copyright (c) 2023 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

version: 2.1

env: &env
  TERM: dumb
  CI: "true"
  USER: circleci

jobs:
  build:
    docker:
    - image: cimg/base:2021.04
    environment:
      <<: *env
    steps:
      - checkout
      - run:
         name: build
         command: |
           set -euo pipefail

           echo "Success!"

workflows:
  version: 2
  build:
    jobs:
    - build
