---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-sequencer
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  sequencer.conf: |
    canton {
      sequencers {
        {{ .Values.common.sequencerName }} {
          {{- include "canton.storage" (list . "sequencer") | indent 10 }}

          public-api {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.public }}
            {{- if .Values.common.tls.public.enabled }}
            tls {
              cert-chain-file = {{ .Values.common.tls.public.chain | quote }}
              private-key-file = {{ .Values.common.tls.public.key | quote }}
              minimum-server-protocol-version = {{ include "canton.tls.minimumServerProtocolVersion" .Values.common.tls.public.minimumServerProtocolVersion }}
              ciphers = {{ include "canton.tls.ciphers" .Values.common.tls.public.ciphers }}
            }
            {{- end }}
          }

          admin-api {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.admin }}
            {{- include "canton.tls.admin" (list .Values.common.tls.admin .Values.common.mtls.admin) | indent 12 }}
          }

          sequencer {
            type = {{ .Values.sequencer.type }}
            high-availability.enabled = true
            {{- with .Values.sequencer.config }}
            config {
              {{- . | nindent 14 }}
            }
            {{- end }}
          }

          monitoring.grpc-health-server {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.health }}
          }
        }
      }

      {{- include "canton.monitoring" (list . "sequencer") | nindent 6 }}
    }
