---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "canton-node.fullname" . }}-sequencer
  labels: {{- include "canton-node.labels" (list . "common") | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  sequencer.conf: |
    canton {
      sequencers {
        {{ .Values.common.sequencerName }} {
          {{- include "canton-node.storage" (list . "sequencer") | indent 10 }}

          public-api {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.public }}
            {{- include "canton-node.sequencerPublicTLS" (list .Values.common.tls.public) | indent 12 }}
          }

          admin-api {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.admin }}
            {{- include "canton-node.adminTLS" (list .Values.common.tls.admin) | indent 12 }}
          }

          sequencer {
            type = database
            high-availability {
              enabled = true
            }
          }

          monitoring.grpc-health-server {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.health }}
          }
        }
      }

      {{ include "canton-node.remote-mediators" . | nindent 6 | trim }}

      {{- include "canton-node.monitoring" (list . "sequencer") | nindent 6 }}
    }
