---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-sequencer
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  sequencer.conf: |
    canton {
      sequencers {
        {{ .Values.common.sequencerName }} {
          {{- include "canton.storage" (list . "sequencer") | indent 10 }}

          public-api {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.public }}
            {{- include "canton.sequencer.tls.public" (list .Values.common.tls.public) | indent 12 }}
          }

          admin-api {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.admin }}
            {{- include "canton.tls.admin" (list .Values.common.tls.admin) | indent 12 }}
          }

          sequencer {
            type = database
            high-availability {
              enabled = true
            }
          }

          monitoring.grpc-health-server {
            address = "0.0.0.0"
            port = {{ .Values.sequencer.ports.health }}
          }
        }
      }

      {{ include "canton.remoteMediators" . | nindent 6 | trim }}

      {{- include "canton.monitoring" (list . "sequencer") | nindent 6 }}
    }
