{{- if or .Values.common.environment .Values.sequencer.environment }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-sequencer-envmap
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
{{- range $key,$value := mustMergeOverwrite .Values.common.environment .Values.sequencer.environment }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
