{{- if .Values.sequencer.ingressRouteTCP.enabled }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ template "common.fullname" . }}-sequencer
  {{- with .Values.sequencer.ingressRouteTCP.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.sequencer.ingressRouteTCP.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.sequencer.ingressRouteTCP.entryPoints }}
  entryPoints: {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: HostSNI(`{{ .Values.sequencer.ingressRouteTCP.hostSNI }}`)
      services:
        - name: {{ template "common.fullname" . }}-sequencer
          port: public
  {{- with .Values.sequencer.ingressRouteTCP.tls }}
  tls: {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
