{{- if or .Values.common.environmentSecrets .Values.sequencer.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname" . }}-sequencer-secretmap
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $key,$value := mustMergeOverwrite .Values.common.environmentSecrets .Values.sequencer.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
