{{- if or .Values.common.environmentSecrets .Values.sequencer.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "canton-node.fullname" . }}-sequencer-secretmap
  labels: {{- include "canton-node.labels" (list . "sequencer") | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $key,$value := mustMergeOverwrite .Values.common.environmentSecrets .Values.sequencer.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
