---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-sequencer
  {{- with .Values.sequencer.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.sequencer.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.sequencer.service.type }}
  ports:
    - name: public
      protocol: TCP
      port: {{ .Values.sequencer.service.ports.public }}
      targetPort: public
    - name: admin
      protocol: TCP
      port: {{ .Values.sequencer.service.ports.admin }}
      targetPort: admin
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.sequencer.service.ports.metrics }}
      targetPort: metrics
    {{- end }}
  {{- if .Values.sequencer.service.sessionAffinity.enabled }}
  sessionAffinity: "ClientIP"
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.sequencer.service.sessionAffinity.timeout }}
  {{- end }}
  selector: {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
