{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.serviceAccountName" (list . "sequencer") }}
  {{- with .Values.sequencer.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: sequencer
    {{- with .Values.sequencerLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.sequencer.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.sequencer.serviceAccount.automountServiceAccountToken }}
secrets:
  {{- with .Values.sequencer.storage.existingSecret.name }}
  - name: {{ . }}
  {{- end }}
  {{- if .Values.environmentSecrets }}
  - name: {{ template "common.fullname" . }}-sequencer-secretmap
  {{- end }}
  {{- with .Values.sequencer.serviceAccount.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
