{{/* Used in deployment-console.yaml, bootstrap/job.yaml */}}
{{- if or .Values.bootstrap.enabled .Values.console.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-remote
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: common
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  remote.conf: |
    canton {
      {{- with .Values.common.features }}
      features {
        enable-preview-commands = {{ .enablePreviewCommands }}
        enable-testing-commands = {{ .enableTestingCommands }}
        enable-repair-commands = {{ .enableRepairCommands }}
      }
      {{- end }}

      remote-domain-managers {
        {{ .Values.common.domainName }} {
          admin-api {
            address = "{{ template "common.fullname" . }}-manager.{{ .Release.Namespace }}.svc.cluster.local"
            port = {{ .Values.manager.service.ports.admin }}
            {{- include "canton.tls.remote" (list .Values.common.tls.admin) | indent 12 }}
          }
        }
      }

      {{ include "canton.remoteMediators" . | nindent 6 | trim }}

      {{ include "canton.remoteSequencers" . | nindent 6 | trim }}

      {{ include "canton.remoteParticipants" . | nindent 6 | trim }}
    }
{{- end }}
