{{/* Used in deployment-console.yaml, bootstrap/job.yaml */}}
{{- if or .Values.bootstrap.enabled .Values.console.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-remote
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: common
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  remote.conf: |
    canton {
      {{- with .Values.common.features }}
      features {
        enable-preview-commands = {{ .enablePreviewCommands }}
        enable-testing-commands = {{ .enableTestingCommands }}
        enable-repair-commands = {{ .enableRepairCommands }}
      }
      {{- end }}

      remote-domain-managers {
        {{ .Values.common.domainName }} {
          admin-api {
            address = {{ include "manager.serviceDNS" . | quote }}
            port = {{ .Values.manager.service.ports.admin }}
            {{- include "canton.tls.remote" (list .Values.common.tls.admin .Values.common.mtls.admin) | indent 12 }}
          }
        }
      }

      remote-mediators {
        {{ .Values.common.mediatorName }} {
          admin-api {
            address = {{ include "mediator.serviceDNS" . | quote }}
            port = {{ .Values.mediator.service.ports.admin }}
            {{- include "canton.tls.remote" (list .Values.common.tls.admin .Values.common.mtls.admin) | indent 12 }}
          }
        }
      }

      remote-sequencers {
        {{ .Values.common.sequencerName }} {
          public-api {
            address = {{ include "sequencer.serviceDNS" . | quote }}
            port = {{ .Values.sequencer.service.ports.public }}
            {{- if .Values.common.tls.public.enabled }}
            transport-security = true
            {{- with .Values.common.tls.public.ca }}
            custom-trust-certificates.pem-file = {{ . | quote }}
            {{- end }}
            {{- end }}
          }
          admin-api {
            address = {{ include "sequencer.serviceDNS" . | quote }}
            port = {{ .Values.sequencer.service.ports.admin }}
            {{- include "canton.tls.remote" (list .Values.common.tls.admin .Values.common.mtls.admin) | indent 12 }}
          }
        }
      }

      {{ include "remoteParticipants" . | nindent 6 | trim }}
    }
{{- end }}
