---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-manager
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  manager.conf: |
    canton {
      domain-managers {
        {{ .Values.common.domainName }} {
          {{- include "canton.storage" (list . "manager") | indent 10 }}

          admin-api {
            address = "0.0.0.0"
            port = {{ .Values.manager.ports.admin }}
            {{- include "canton.tls.admin" (list .Values.common.tls.admin .Values.common.mtls.admin) | indent 12 }}
          }

          init.domain-parameters.unique-contract-keys = {{ .Values.manager.uniqueContractKeys }}

          topology.open = {{ .Values.manager.topology.open }}

          replication.enabled = true

          {{- if .Values.common.kms.enabled }}
          {{- include "canton.kms" (list . "manager") | indent 10 }}
          {{- end }}

          monitoring.grpc-health-server {
            address = "0.0.0.0"
            port = {{ .Values.manager.ports.health }}
          }
        }
      }

      {{- include "canton.monitoring" (list . "manager") | nindent 6 }}
    }
  {{- with .Values.manager.configOverride }}
  manager-override.conf: |
  {{- . | nindent 4 }}
  {{- end }}
  {{- with .Values.manager.bootstrapScript }}
  manager.canton: |
  {{- . | nindent 4 }}
  {{- end }}
