---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-manager
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  manager.conf: |
    canton {
      domain-managers {
        {{ .Values.common.domainName }} {
          {{- include "canton.storage" (list . "manager") | indent 10 }}

          admin-api {
            address = "0.0.0.0"
            port = {{ .Values.manager.ports.admin }}
            {{- include "canton.tls.admin" (list .Values.common.tls.admin) | indent 12 }}
          }

          replication {
            enabled = true
          }

          monitoring.grpc-health-server {
            address = "0.0.0.0"
            port = {{ .Values.manager.ports.health }}
          }

          topology {
            open = {{ .Values.manager.topology.open }}
            require-participant-certificate = {{ .Values.manager.topology.requireParticipantCertificate }}
          }
        }
      }

      {{ include "canton.remoteMediators" . | nindent 6 | trim }}

      {{ include "canton.remoteSequencers" . | nindent 6 | trim }}

      {{- include "canton.monitoring" (list . "manager") | nindent 6 }}
    }
