---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}-manager
  {{- with .Values.manager.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.manager.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.manager.replicaCount }}
  selector:
    matchLabels: {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: manager
  strategy:
    type: "Recreate"
  template:
    metadata:
      annotations:
        "checksum/config": {{ include (print $.Template.BasePath "/manager/configmap.yaml") . | sha256sum | quote }}
        "checksum/env": {{ include (print $.Template.BasePath "/manager/configmap-env.yaml") . | sha256sum | quote }}
        "checksum/secret": {{ include (print $.Template.BasePath "/manager/secret-env.yaml") . | sha256sum | quote }}
        {{- with .Values.manager.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: manager
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.manager.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "common.serviceAccountName" (list . "manager") }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: canton
          image: {{ include "common.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          args:
            - "daemon"
            - "--log-profile=container"
            - "--log-encoder={{ .Values.common.logEncoder }}"
            - "--log-level-root={{ .Values.common.logLevel.root }}"
            - "--log-level-canton={{ .Values.common.logLevel.canton }}"
            - "--log-level-stdout={{ .Values.common.logLevel.stdout }}"
            - "--config=/canton/manager.conf"
          envFrom:
            {{- if or .Values.common.environment .Values.manager.environment }}
            - configMapRef:
                name: {{ include "common.fullname" . }}-manager-envmap
            {{- end }}
            {{- if or .Values.common.environmentSecrets .Values.manager.environmentSecrets }}
            - secretRef:
                name: {{ include "common.fullname" . }}-manager-secretmap
            {{- end }}
          env:
          {{- if .Values.manager.storage.existingSecret.name }}
            - name: CANTON_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.manager.storage.existingSecret.name }}
                  key: {{ .Values.manager.storage.existingSecret.key }}
          {{- end }}
          ports:
            - name: admin
              containerPort: {{ .Values.manager.ports.admin }}
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.manager.ports.metrics }}
            {{- end }}
          {{- with .Values.manager.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
          {{- if .Values.manager.livenessProbe }}
            {{- toYaml .Values.manager.livenessProbe | nindent 12 }}
          {{- else }}
            grpc:
              port: {{ .Values.manager.ports.health }}
              service: "liveness"
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 3
          {{- end }}
          readinessProbe:
          {{- if .Values.manager.readinessProbe }}
            {{- toYaml .Values.manager.readinessProbe | nindent 12 }}
          {{- else }}
            grpc:
              port: {{ .Values.manager.ports.health }}
              service: ""
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 1
            timeoutSeconds: 3
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /canton/manager.conf
              subPath: manager.conf
              readOnly: true
            {{- if .Values.common.tls.admin.enabled }}
            - name: tls-admin
              mountPath: "/tls-admin"
              readOnly: true
            {{- if .Values.common.mtls.admin.enabled }}
            - name: mtls-admin
              mountPath: "/mtls-admin"
              readOnly: true
            {{- end }}
            {{- end }}
            {{- if .Values.storage.certificatesSecret }}
            - name: pgtls
              mountPath: "/pgtls"
              readOnly: true
            {{- end }}
            {{- with .Values.manager.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" . }}-manager
        {{- if and .Values.common.tls.admin.enabled .Values.common.tls.admin.certManager.issuerName }}
        {{- include "certManager.csi" (list . "manager" "tls-admin" .Values.common.tls.admin.certManager (include "manager.serviceDNS" .)) | indent 8 }}
        {{- if and .Values.common.mtls.admin.enabled .Values.common.mtls.admin.certManager.issuerName }}
        {{- include "certManager.csi" (list . "manager" "mtls-admin" .Values.common.mtls.admin.certManager "") | indent 8 }}
        {{- end }}
        {{- end }}
        {{- if .Values.storage.certificatesSecret }}
        - name: pgtls
          secret:
            secretName: {{ .Values.storage.certificatesSecret }}
        {{- end }}
        {{- with .Values.manager.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.manager.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.manager.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
