{{- if or .Values.common.environmentSecrets .Values.manager.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "canton-node.fullname" . }}-manager-secretmap
  labels: {{- include "canton-node.labels" (list . "manager") | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $key,$value := mustMergeOverwrite .Values.common.environmentSecrets .Values.manager.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
