---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.fullname" . }}-manager
  {{- with .Values.manager.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.manager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.manager.service.type }}
  ports:
    - name: admin
      protocol: TCP
      port: {{ .Values.manager.service.ports.admin }}
      targetPort: admin
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.manager.service.ports.metrics }}
      targetPort: metrics
    {{- end }}
  selector: {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: manager
