{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.serviceAccountName" (list . "manager") }}
  {{- with .Values.manager.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
    {{- with .Values.managerLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.manager.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.manager.serviceAccount.automountServiceAccountToken }}
secrets:
  {{- with .Values.manager.storage.existingSecret.name }}
  - name: {{ . }}
  {{- end }}
  {{- if .Values.environmentSecrets }}
  - name: {{ template "common.fullname" . }}-manager-secretmap
  {{- end }}
  {{- with .Values.manager.serviceAccount.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
