{{- if and .Values.console.enabled .Values.console.environmentSecrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.fullname" . }}-console-secretmap
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
{{- range $key,$value := .Values.console.environmentSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
