{{- if .Values.common.networkpolicy.enabled }}
{{/*
networkpolicy to allow access to the ledger API, and the metrics
*/}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.fullname" . }}-allow-ledger-api-metrics
  {{- with .Values.console.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.common.networkpolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: participant
      canton.io/participant: {{ .Values.participantName }}
  policyTypes:
  - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.service.ports.public }}
        {{- if .Values.metrics.enabled }}
        - protocol: TCP
          port: {{ .Values.service.ports.metrics }}
        {{- end }}
{{- end }}
