{{- if .Values.common.networkpolicy.enabled }}
{{/*
networkpolicy to allow access from inside the namespace
*/}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.fullname" . }}-allow-same-namespace
  {{- with .Values.console.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.common.networkpolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ .Release.Namespace }}
{{- end }}
