{{- if and .Values.common.networkpolicy.enabled .Values.metrics.enabled }}
{{/*
networkpolicy to allow access to the sequencer API
*/}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "common.fullname" . }}-allow-manager-metrics
  {{- with .Values.console.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.common.networkpolicy.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: manager
      canton.io/domain: {{ .Values.common.domainName }}
  policyTypes:
  - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.manager.service.ports.metrics }}
{{- end }}
