{{/*
Basic console pod with Canton configuration to reach this participant
Mostly used for troubleshooting and to run Canton scripts manually
*/}}
{{- if .Values.console.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}-console
  {{- with .Values.console.deployment.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.console.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "common.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: console
  {{- with .Values.console.deployment.strategy }}
  strategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        "checksum/config": {{ include (print $.Template.BasePath "/configmap-remote.yaml") . | sha256sum | quote }}
        "checksum/env": {{ include (print $.Template.BasePath "/console/configmap-env.yaml") . | sha256sum | quote }}
        "checksum/secret": {{ include (print $.Template.BasePath "/console/secret-env.yaml") . | sha256sum | quote }}
        {{- with .Values.console.pod.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{- include "common.labels" . | nindent 8 }}
        app.kubernetes.io/component: console
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.console.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ template "common.serviceAccountName" (list . "console") }}
      {{- end }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.console.terminationGracePeriodSeconds }}
      {{- if .Values.console.pod.securityContext.enabled }}
      securityContext: {{- omit .Values.console.pod.securityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: console
          image: {{ include "console.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.console.securityContext.enabled }}
          securityContext: {{- omit .Values.console.securityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          command: ["tail", "-f", "/dev/null"]
          envFrom:
            {{- if .Values.console.environment }}
            - configMapRef:
                name: {{ include "common.fullname" . }}-console-envmap
            {{- end }}
            {{- if .Values.console.environmentSecrets }}
            - secretRef:
                name: {{ include "common.fullname" . }}-console-secretmap
            {{- end }}
          {{- with .Values.console.resources }}
          resources: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /etc/canton
              readOnly: true
            {{- if .Values.common.tls.public.enabled }}
            - name: tls-public
              mountPath: /tls-public
              readOnly: true
            {{- end }}
            {{- if .Values.common.tls.admin.enabled }}
            - name: tls-admin
              mountPath: /tls-admin
              readOnly: true
            {{- if .Values.common.mtls.admin.enabled }}
            - name: mtls-admin
              mountPath: /mtls-admin
              readOnly: true
            {{- end }}
            {{- end }}
            {{ include "remoteParticipants.volumeMounts" . | nindent 12 | trim }}
            {{- with .Values.console.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "common.fullname" . }}-remote
        {{- if and .Values.common.tls.public.enabled .Values.common.tls.public.certManager.issuerName }}
        # Dummy certificate only used to mount the root CA certificate
        {{- include "certManager.csi" (list . "console" "tls-public" .Values.common.tls.public.certManager "") | indent 8 }}
        {{- end }}
        {{- if and .Values.common.tls.admin.enabled .Values.common.tls.admin.certManager.issuerName }}
        # Dummy certificate only used to mount the root CA certificate
        {{- include "certManager.csi" (list . "console" "tls-admin" .Values.common.tls.admin.certManager "") | indent 8 }}
        {{- if and .Values.common.mtls.admin.enabled .Values.common.mtls.admin.certManager.issuerName }}
        {{- include "certManager.csi" (list . "console" "mtls-admin" .Values.common.mtls.admin.certManager "") | indent 8 }}
        {{- end }}
        {{- end }}
        {{ include "remoteParticipants.volumes" (list . "console") | nindent 8 | trim }}
        {{- with .Values.console.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.console.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.console.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
