{{- if and .Values.console.enabled .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "common.serviceAccountName" (list . "console") }}
  {{- with .Values.console.serviceAccount.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
    {{- with .Values.consoleLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.console.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.console.serviceAccount.automountServiceAccountToken }}
secrets:
  {{- if .Values.environmentSecrets }}
  - name: {{ template "common.fullname" . }}-console-secretmap
  {{- end }}
  {{- with .Values.console.serviceAccount.extraSecrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
